### ISSUE TITLE
React v17 へのマイグレーション

### ISSUE THREAD

**Issue by 0918nobita** [ruritoBlogger/Sanbaka_1.5_fan_site#114]
## 概要

`react-jsx`, `react-jsxdev` という新しい jsx 変換方式が追加されたので、現状の `"jsx": "react"` からそちらに移行する

## なぜ

- 従来の `React.createElement` に変換する方式で問題があった、children の扱いがシンプルになる
- JSX記法でコードを書く時に、JSX記法を使うためだけに `import React from 'react'` する必要がなくなる

## どうやって

- 各種依存パッケージのアップデート
  - `typescript` (v4.1〜)
  - `react`
  - `react-dom`
  - `react-headroom`
  - `react-device-detect`
  - `@material-ui/core`
  - `@material-ui/icons`
  - `@types/react`
  - `@types/react-dom`
- `@babel/preset-react` のコンフィグ修正
  - 参考：https://ja.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#manual-babel-setup

## 参考記事

- React v17.0 - React Blog https://ja.reactjs.org/blog/2020/10/20/react-v17.html
- React 17におけるJSXの新しい変換を理解する https://zenn.dev/uhyo/articles/react17-new-jsx-transform

**Comment by ruritoBlogger** [comment]
一通り貼ってもらった記事に目を通してみます
ありがとう
