### ISSUE TITLE
自動デプロイを行う

### ISSUE THREAD

**Issue by ruritoBlogger** [ruritoBlogger/Sanbaka_1.5_fan_site#5]
やること
- [ ] #2 を行う
- [ ] #3 を行う
- [ ] #4 を行う
- [ ] dockerのコンテナを参照してデプロイする方法を調査する
- [ ] 必要があればfirebaseとは別のhosting serviceへの移行を考える
- [ ] 自動デプロイ用のスクリプトを実装する

**Comment by 0918nobita** [comment]
- **GitHub Actions** なら Firebase Hosting に自動デプロイできて便利
- Firebase Hosting 以外の選択肢としては、Netlify, Vercel がオススメ (どちらも OSS なら無料で使える)
  - **Netlify** : リポジトリと紐づけて、特定のブランチへの push を検知して自動デプロイできる。**設定が簡単**。ただしバックエンドはデプロイできず、あくまで静的ファイルをホスティングするもの
  - **Vercel** : バックエンドのデプロイができる (Node.js, Python, Go, Ruby に対応)。込み入った設定をしようとすると少々面倒だが、有名な各フレームワークに対して設定のテンプレートが用意されていて、普通に使うぶんには楽ちん。特に **Next.js との相性が良い** (Next.js は Vercel が作ってる React フレームワークなのでそれはそう)

**Comment by ruritoBlogger** [comment]
@0918nobita 今気付いた...申し訳ねぇ...

今はVercelでデプロイやってるので閉じますね。(SSGに移行出来たらfirebaseに移行するのもあり)
